import = [
  "~/.config/alacritty/themes/one_dark.toml"
]

[font]
size = 14.0

[font.bold]
family = "Delugia"
style = "Bold"

[font.bold_italic]
family = "Delugia"
style = "Bold Italic"

[font.italic]
family = "Delugia"
style = "Italic"

[font.normal]
family = "Delugia"
style = "Regular"
